Fix bug

diff --git a/bin/send-sitemap b/bin/send-sitemap
--- a/bin/send-sitemap
+++ b/bin/send-sitemap
@@ -1,4 +1,11 @@
 #!/bin/bash
 
-set -ue
-exit http get 'https://www.google.com/ping?sitemap=https://blog.mothule.com/sitemap.xml'
+ret=`http -h get 'https://www.google.com/ping?sitemap=https://blog.mothule.com/sitemap.xml' | head -n 1 | awk '{ print $2 }' | xargs`
+
+if [[ ret == 200 ]] ; then
+  echo 'Successful'
+  exit 0
+else
+  echo 'Failed'
+  exit 1
+fi
